### ISSUE TITLE
I am getting an error in the web app which appears to be some wrong reference or dll usage

### ISSUE THREAD

**Issue by badalk** [toddkitta/CortanaIntelligenceSuiteWorkshopManual#13]
This occurs post deployment. I faced two issues.
1. The app settings are not persisted so I had to create them manually (mlApiKey, mlServiceID etc..), without which, call to weather API used to throw invalid API key error
2. Post that the original error is gone but I see the error below..

Method not found: 'System.Threading.Tasks.Task`1<System.Net.Http.HttpResponseMessage> System.Net.Http.HttpClientExtensions.PostAsJsonAsync(System.Net.Http.HttpClient, System.String, !!0)'.

Regards
Badal

**Comment by toddkitta** [comment]
Can you please let me know the steps you took and what led up to this error? Screenshots also help.

**Comment by badalk** [comment]
Unfortunately I deleted my resource group and cannot provide screenshot, as anyway it was the last piece of the whole exercise.

I followed exactly the same steps given in the manual and in the videos. Until that point everything was working including the PowerBI part.

Regards
Badal

**Comment by toddkitta** [comment]
I'm sorry to hear that. I am always on the lookout for issues people are having here. I will be on the lookout for issues in this area going forward.
