### ISSUE TITLE
Issue with creating New Web Service

### ISSUE THREAD

**Issue by murateri** [toddkitta/CortanaIntelligenceSuiteWorkshopManual#8]
While trying to Deploy Web Service for AdventureWorks Travel [Predictive Exp.] I do not have what is in your video : Deploy Web Service (New) preview
When clicking on Deploy Web Service I stay in Microsoft Azure Machine Learning Studio and come to Web Service Tab
![maml studio web services](https://cloud.githubusercontent.com/assets/25083483/21896985/86dd0a10-d8e8-11e6-8cef-82e37c0a557c.png)
If I go to New Web Service Experience I have no Use Web Service link in Quickstart
![maml web services](https://cloud.githubusercontent.com/assets/25083483/21897064/c27c3e1a-d8e8-11e6-8a1e-0b0466683137.png)
Can you help me ?
Eric

**Comment by toddkitta** [comment]
@murateri: are you still having this issue? Is it possible that you are using an ML workspace that is different from the one that was created when deploying the workshop prerequisites (http://aka.ms/cortanasetup)? I have seen that if you use an older workspace (i.e. one that was created a long time ago), you may see different behavior like you describe. Can you confirm?

**Comment by murateri** [comment]
@toddkitta: I just surrendered on this (have to do other stuff at the moment)... did not went through the exercice but I will look at the videos to understand the whole interesting things about MS Machine Learning capabilities

**Comment by toddkitta** [comment]
Ok - thanks for the follow. From what I have seen, if you use a newly created ML Workspace, everything should work. I'll close this issue, but if you happen to come across it again, please let me know. Thank you!

**Comment by murateri** [comment]
Thanks for your feedback also
